### ISSUE TITLE
Need Python Voice Assistant

### ISSUE THREAD

**Issue by arpanghosh2416** [dsc-iem/Flat-Booking-Website-HacktoberFest22#10]
A vpa is needed for this website for my future planning purpose and enhancement is needed.

**Comment by aniketshaw29** [comment]
I have little prior exp in this part. I would like to contribute.

**Comment by arpanghosh2416** [comment]
Ok @aniketshaw29 I am assigning this issue to you.

**Comment by arpanghosh2416** [comment]
Ok
