### ISSUE TITLE
Need a frontend based on Angular

### ISSUE THREAD

**Issue by arpanghosh2416** [dsc-iem/Flat-Booking-Website-HacktoberFest22#11]
A full professional website needed based on Angular. The Structure is required only.

**Comment by supratim531** [comment]
I can do the structure which is needed as I know Angular

**Comment by arpanghosh2416** [comment]
Ok @supratim531 . I am assigning it to u now.

**Comment by arpanghosh2416** [comment]
Thank You @supratim531
