### ISSUE TITLE
Need Java with Spring Boot with Service Layer

### ISSUE THREAD

**Issue by arpanghosh2416** [dsc-iem/Flat-Booking-Website-HacktoberFest22#3]
Please add a Service layer with the following Entity and Repository Layer.
Specifications are:

- CustomUserDetailsService.java
- FeedbackService.java
- FlatService.java
- OwnerService.java
- UserService.java

**Comment by mriganka56** [comment]
Hi @arpanghosh2416 
I would like to contribute to the Service Layer.
Can I?

**Comment by arpanghosh2416** [comment]
Ok @mriganka56 I am assigning it to you.

**Comment by mriganka56** [comment]
Ok doing it

**Comment by arpanghosh2416** [comment]
Thank You @mriganka56
