### ISSUE TITLE
Need Java Security layer along with the previous architecture.

### ISSUE THREAD

**Issue by arpanghosh2416** [dsc-iem/Flat-Booking-Website-HacktoberFest22#5]
Provide me a Security Layer for Web Security Configuration.

**Comment by mriganka56** [comment]
@arpanghosh2416 can I contribute in the security layer?

**Comment by arpanghosh2416** [comment]
Ok sure @mriganka56

**Comment by arpanghosh2416** [comment]
Thank You Again for Contributing. @mriganka56 . Please be ready with the JWT part as security related thing.
